print ("MI PRIMER HOLA MUNDO EN PYTHON")
print ("APUNTES")


print ("PYTHON ES UN LENGUAJE EXTREMADAMENTE ORDENADO TENEMOS QUE TENER CUIDADO CON LOS ESPACIOS ")
# print ("HOLA MUNDO")  MODO CORRECTO
#  print ("MUNDO") MODO INCORRECTO POR EL ESPACIO AL COMIENZO 
print ("LA SEMANTICA ES NECESARIA NO ES BUENA PRACTICA HACER UNA FUNCION QUE RCIBA NUMEROS Y REGRESE LETRAS O EN LA DECLARACION DE LAS") 
print ("VARIABLES EL NOMBRE DE LAS VARIABLES TIENE ESTAR RELACIONADO CON LO QUE VA A GUARDAR ESA VARIABLE ")

print ("DECLARACION DE VARIABLES _____")

print ("PYTHON NO PERMITE GENERAR VARIABLES QUE INICIEN CON NUMEROS ")
print("EJEMPLO EN EL CODIGO")

# 1nombre = "CARLITOSXC"  --> ERROR
nota = "PERO SI PUEDEN COMENZAR CON LETRAS SEGUIDO DE NUMEROS" #VARIABLE 
print (nota)

# n1ombre = ""

mens_1 = "Te doy la bienvenida al Coding Playground"
mens_2 = "Mi primer print"
mens_3 = "30 "

print (mens_1, mens_2,mens_3 )


