#operadores numericos
a = 10
b = 3

print ("SUMA:" , a + b)
print ("RESTA:" , a - b)
print ("MULTIPLICACION:" , a * b)
print ("DIVISION:" , a / b)


# MODULO VAMOS CASOS DONDE QUEREMOS OBTENER EL RESTO DE UNA DIVISION PARA ELLO UTILIZAMOS LOS MODULOS
# WARNING!!! DEBEMOS DE TENER CUIDADO CUANDO HACEMOS ALGUNAS OPERACIONES COMO DIVIDIR ENTRE 0 
print ("MODULO:" , a % b)

# DOBLE DIVISION SOLO MUESTRA LA PARTE ENTERA DE LA DIVISION EN EL APARTADO DEL MODULO 
print ("PARTE ENTERA DE LA DIVISION:" , a // b)

# POTENCIACION ES ELEVAR A LA POTENCIA 
print ("POTENCIACION:" , a ** b)

# EXISTENA OPERACIONES QUE PODEMOS USAR DE MANERA MAS CONSISA ESTAS SE LLAMAN SHORTCUTS SE PUEDE HACER CON LOS DEMAS OPERADORES 
# + - / *
print ("SHORTCUTS:")
a =+ 2
print (a) 

# P E M D A S ES EL ORDEN QUE DEBEMOS LLEVAR CON OPERACIONES MATEMATICAS COMPLEJAS EN NUESTRAS PRACTICAS FUTURAS 
# POTENCIACION
# EXPONENCIACION
# MATEMATICAS
# DIVISION 
# ADICION 
# SUSTRACION

operation_1 = 2 + 3 * 4
operation_2 = (2 + 3) * 4
print (operation_1)
print (operation_2)

operation_3 = (2 + 3) * (4 ** 2) / 8 - 1
print (operation_3)




