# CUANDO QUEREMOS COPIAR EL VALOR DE UNA VARIABLE EN PYTHON PODEMOS COPIAR EL ELEMENTO PERO DESDE EL ESPACIO EN MEMORIA 
a = [1,2,3,4,5]
b = a 

print (a)
print (b)

del a[0] #LO ELIMINA DE AMBAS VARIABLES NO SOLO DE "a"

print (a)
print (b)

# PARA PODER VER EN DONDE SE ESTA ALMACENANDO LA INFORMACION EL LA MEMORIA USAMOS LA FUNCION ID
print ("ESPACIO EN LA MEMORIA QUE UTILIZAN LAS VARIABLES ")
print (id (a))
print (id (b))

# COMO AMBAS VARIABLES ESTAN EN EL MISMO ESPACIO DE MEMORIA AL MODIFICAR UNA LA OTRA TAMBIEN SE VE AFECTADA 
# POR LO CUAL PODEMOS USAR EL SLICING
print ("AQUI C YA UTILIZA UN ESPACIO DIFERENTE EN MEMORIA ")
c = a [:] # CUANDO DEFINIMOS (CON LOS CORCHETES []) DESDE DONDE VAMOS A COPIAR LA INFORMACION AL MODIFICAR LA VARIABLE ESTO NO AFECTA A LA OTRA 
print (id (a))
print (id (b))
print (id (c))

a.append(6)
print ("VALOR DE A: ")
print (a)
print ("VALOR DE C: ")
print (c)

