# FUNCION INPUT PARA RECIBIR INFORMACION DE TECLADO DEL USUARIO
# CREAMOS UNA VARIABLE CON LA FUNCION INPUT Y UN MENSAJE PARA PODER GUARDAREN ELLA LA INFORMACION 
# EL RESULTADO DE USAR LA FUNCION INPUT SIEMPRE GUARDARA UN DATO DE TIPO STRING NOSOTROS TENEMOS QUE HACER EL CAMBIA AL TIPO DE DATO QUE NECESITEMOS
# CASTING ES EL CAMBIO DE TIPO DE DATO COMO EJEMPLO EN LAS VARIABLES "edad" Y "edad_2" PONEMOS EL TIPO DE DATO NECESARIO 


nombre = input("INGRESE SU NOMBRE: ")
edad = int(input ("INGRESE SU EDAD: "))
edad_2 = float(input ("TIEMPO PROGRAMANDO: "))

print (nombre)
print (edad)
print (edad_2)
print (type (nombre))
print (type (edad))
print (type (edad_2))


