# PODEMOS USAR FILAS DENTRO DE FILAS ESTAS SE LLAMARAN MATRICES 
# LAS MATRICES TIENES LAS MISMAS PROPIEDADES QUE LAS LISTAS 
# ES DECIR PODEMOS ELIMINAR/AGREGAR ELEMENTOS
# PERO EXISTEN LISTAS/MATRICES LAS CUALES SON MUTABLES O INMUTABLES 
# MUTABLE => SE PUEDE MODIFICAR SU CONTENIDO 
# INMUTABLE => NO SE PUEDE MODIFICAR SU CONTENIDO
 

matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]]

print (matrix)
print (matrix[0])


# TUPLAS
print("TUPLAS EN PYTHON _________OwO")
numbers = (1,2,3,4,5)
print (numbers)
print (type (numbers))
# SI TE DAS CUENTA EL TIPO DE DATO MARCA COMO tuple =>TUPLA SI CAMBIAMOS EL TIPO DE DATO MARCARA UN ERROR 
numbers[0] = 'uno' #DE ESTA FORMA PODEMOS MODIFICAR UN ELEMENTO CON EL APOYO DE LA INDEXACION 
print(numbers)


