# LAS FUNCIONES NOS SIRVE PARA GUARDAR PORCIONES DE LOGICA 
# QUE TIENEN UNA TAREA EN ESPECIFICO DE ESTA MANERA NO SE DUPLICA CODIGO 
# LAS FUCNIONES SE DEFINEN USANDO LA PALABRA RESERVADA 
# def 
# SEGUIDO DEL NOMRE DE LA FUNCION 
# def ejemplo_funcion 
# Y LOS PARAMETROS QUE ESTA LLEVARA}

def greet(name, last_name="EL CARILLA DE PERRO"):
    print("HOLA", name, last_name)

greet("CARLOS","LOPEZ") # RECUERDA QUE LAS FUCIONES TIENE QUE SER LLAMADAS
greet("RODRI")



# CUANDO MANDAMOS A LLAMAR A LA FUNCION LE PODEMOS ASIGNAR LOS VALORES QUE ESTA NECESITA PARA REALIZAR LA OPERACION
# EN OTRO CASO PODEMOS ASIGNARLE UN VALOR EN LA MISMA FUNCION Y NO EN EL LLAMAMIENTO