def sum_numbers(*args):#CREAMOS UNA FUNCION QUE SUME NUEMROS DONDE EL PARAMETRO SON LOS args
    return sum(args)# RETORNAMOS LA SUMA DE TODOS LOS ELEMENTOS 

print(sum_numbers(1,2,3,4,5))
print(sum_numbers(1,2))
print(sum_numbers(1,2,3,4,5,7,8,9,10))


"""
args SU ESTRUCTURA ES LA SIGUIENTE  *VARIABLE POR BUENAS PRACTICAS SE PONE EN EL NOMBRE DE LA VARIABLE args 
args HAY CASOS DONDE NO SABEMOS CUANTOS DATOS SON CON LOS QUE VAMOS A TRABAJAR(PARAMETROS) LA VARIBLE QUE DEFINIMOS args
ES DE TIPO TUPLA ESTO QUIERE DECIR QUE NO ES MUTABLE/NO SE MODIFICA 
EN ELLA SE ALMACENA LA INFORMACION NECESARIA SIN SABER CUANTOS DATOS VA A RECIBIR 

CUANDO NOSOTROS PASAMOS LOS PARAMETROS Y NO ESPECIFICAMOS LA POSICION O LA VARIABLE DONDE QUEREMOS ALMACENAR 
AQUI USAMOS LOS args 

LOS kwargs SON LO OPUESTO EN ELLOS NOSOTROS DEFINIMOS LA POSICION DE DONDE SE VA A ALMACENAR LA INFORMACION 


"""