#Desempaquetado args
def add(a, b, c):#FUNCION QUE SUMA 3 VALORES 
    return a + b + c

values = (1, 2, 3)#DEFINIMOS UNA VARIABLE CON TRES VALORES 
print(add(*values))#DEFINIMOS QUE values SEA UN args Y QUE DESEMPAQUETE LOS VALORES ALMACENADOS 

def show_info(name, age):#FUNCION PARA MOSTRAR INFORMACION 
    print(f"Name: {name}, Age: {age}")

data = {"name": "Ana", "age": 28}#DEFINIMOS UNA VARIABLE CON VARIOS VALORES 
show_info(**data)#DEFINIMOS QUE data SEA UN kwargs Y QUE DESEMPAQUETE LOS VALORES ALMACENADOS 


"""
EN LOS args Y LOS kwargs HEMOS PASADO LA INFORMACION DE MANERA DIRECTAMENTE POR PARAMETROS
PERO VA A HABER SITUACIONES DONDE VAMOS A NECESITAR INFROMACION DE UNA VARIABLE EXTERNA EN ESTOS CASOS USAMOS 
LOS DESEMPAQUETADOS 
"""