def print_info(**kwargs):
    for key, value in kwargs.items():
        print(f'{key}: {value}')

print_info(name='Carlos', age=30, city='Bogotá')#AQUI PASAMOS LOS ARGUMETOS POSICIONALES ESTAMOS ESPECIFICANDO DONDE SE DEBEN GUARDAR
print_info(name='Carlos', age=30, city='Bogotá', country = 'Colombia')



"""
kwargs SU ESTRUCTURA ES LA SIGUIENTE  **VARIABLE POR BUENAS PRACTICAS SE PONE EN EL NOMBRE DE LA VARIABLE kwargs 


CUANDO NOSOTROS PASAMOS LOS PARAMETROS Y ESPECIFICAMOS LA POSICION O LA VARIABLE DONDE QUEREMOS ALMACENAR LA INFORMACION
DEL MISMO MODO QUE LOS args NO SABEMOS CUANTOS PARAMETROS VAMOS A RECIBIR PERO SI DEFINIMOS DONDE SE ALMACENARA LA INFORMACION 
YA PROCESADA 
AQUI USAMOS LOS kwargs 


"""