#IDs de empleados
var1 = 120 #FORMA CASUAL 
id1: int = 101 #CON ANOTACIONES 
id2: int = 102

#Sumar los IDs
total_id: int = id1 + id2

#Mostrar resultado
print(total_id)


"""
LAS ANOTACIONES NOS SIRVEN PARA DAR MAS INFORMACION Y PARA DEFINIR EL TIPO DE VARIABLE QUE ESTAMOS USANDO Y CREANDO 
ADEMAS DEL REULTADO DE LAS FUNCIONES PARA PODER DAR UN MEJOR CONTEXTO DE QUE ES LO QUE QUEREMOS HACER 




"""